### PR TITLE
Fix linking to the library on MSYS2/Clang.

### PR DESCRIPTION
**Pull request by williamjcm**
As you asked on Gitter, mosra, this is the PR containing the fix to errors when linking with the SceneGraph library on MSYS2's build of Clang.

### CODE REVIEW

**Comment by mosra** [comment]
Wasn't there also something about the `-Wreturn-type-c-compat` error? Or was that in Corrade?

Not urgent from my side, but if you get a chance to compile the whole thing including tests, there will be probably more linker errors in Audio, Animation etc. that need similar patches.

**Comment by williamjcm** [comment]
> Wasn't there also something about the `-Wreturn-type-c-compat` error? Or was that in Corrade?

`-Wreturn-type-c-linkage`, IIRC, and it was in Corrade.

> Not urgent from my side, but if you get a chance to compile the whole thing including tests, there will be probably more linker errors in Audio, Animation etc. that need similar patches.

I'll give it a spin.

**Comment by williamjcm** [comment]
Added a fix for `Animation::Player`.

**Comment by mosra** [comment]
For the record, as the Gitter history will inevitably get forgotten -- everything builds when applying additional patches needed for Corrade's shared globals as mentioned above, but then `UtilityFatalTest`, all AL and GL tests crash in weird places such as:

```
(gdb) bt
#0  0x000000006fcbd12d in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
#1  0x000000006fd34c39 in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
#2  0x000000006fd397e9 in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
#3  0x0000000068502f30 in Corrade::Utility::(anonymous namespace)::toStream<char const*> (s=...,
    value=@0x65fca8: 0x405004 "Cannot make the definite answer to be")
    at ../src/Corrade/Utility\Debug.cpp:72
#4  0x0000000068542e1c in Corrade::Utility::Debug::print<char const*> (
    this=0x65fd38,
    value=@0x65fca8: 0x405004 "Cannot make the definite answer to be")
    at ../src/Corrade/Utility\Debug.cpp:467
#5  0x0000000068501f0d in Corrade::Utility::Debug::operator<< (this=0x65fd38,
    value=0x405004 "Cannot make the definite answer to be")
    at ../src/Corrade/Utility\Debug.cpp:479
#6  0x00000000004015e2 in main ()
    at ../src/Corrade/Utility/Test\FatalTest.cpp:11
```

Putting this on hold until either Clang improves, the problematic parts (iostreams) go away, or someone finds out why this is happening.

**Comment by mosra** [comment]
@Amphaal So I guess with mosra/corrade#95 fixing the crash merged, this could be merged too? Or did the fixed crash uncover more issues? :)

**Comment by Amphaal** [comment]
> @Amphaal So I guess with [mosra/corrade#95](https://github.com/mosra/corrade/pull/95) fixing the crash merged, this could be merged too? Or did the fixed crash uncover more issues? :)

I think you can. 

There is maybe more work to do regarding non-breaking warnings triggered by Clang10 (I spotted some), but that can be done afterward. I haven't been playing much with Magnum yet, but if the CI tests do pass, I guess you are good to go ;)

**Comment by mosra** [comment]
The patch didn't want to apply anymore, so I did the same with a global find&replace (which uncovered a bunch of other missed cases in the `Audio` lib). Pushed to master as 8a42c727c18400b44d689fbe2a79b507e19a2c89.

**Pull request closed without merging**
