### PR TITLE
FindSDL2: Properly handle target platform architecture on windows

### PR DESCRIPTION
**Pull request by Squareys**
Hi @mosra !

As discussed, here are the changes for the FindSDL2.cmake module. Let's see what the CI says.

Greetings,
Squareys.

PS: There seems to be a commit attached which I did not do... Did you revert master to a commit before per chance?

### CODE REVIEW

**Comment by Squareys** [comment]
@mosra As soon as you declare this as fine, I will copy it over to magnum-examples and do a PR there also.

**Comment by Squareys** [comment]
CIs seem to have properly found SDL2. There is an error on macosx, but that's the "cmake 3.6.0 already installed" one, which was there before.

What's with this commit of yours (946aab3) should I remove it?

**Comment by mosra** [comment]
Heh, but GitHub reports that 946aab3 is here as well ... Weird.

**Comment by mosra** [comment]
Happy with the contents, merged :)

**Pull request merged**
